# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSQuickStartDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'VideoSDKRTC', :git => 'https://github.com/videosdk-live/videosdk-rtc-ios-sdk.git'
  # Pods for iOSQuickStartDemo

end
